configVersion: 4
distance: 10000
message: "§cYou are going too far away!"
messageTp: "§cYou cannot teleport outside the world border!"
messageTpOp: "§6You have passed the world border"
teleportToSpawn: false
checkVehicleMovement: true
opBypass: true
worlds:
  - "world"
